### ISSUE TITLE
Add integration with capitanhook

### ISSUE THREAD

**Issue by RedDevilHat** [alyamovsky/symfony-docker-skeleton#1]
Очень бы хотелось возможность использовать https://github.com/captainhookphp/captainhook

Однако фаил настройки библиотеке должен быть на уровне с .git и при этом иметь доступ к vendor

**Comment by alyamovsky** [comment]
предварительно думаю, что можно добавить. точно скажу, когда немного изучу библиотеку

**Comment by alyamovsky** [comment]
пока что прикрою issue :)
