### ISSUE TITLE
Подкинуть в сборку blackfire

### ISSUE THREAD

**Issue by RedDevilHat** [alyamovsky/symfony-docker-skeleton#2]
https://www.blackfire.io/profiler

Предлагаю запихнуть вот такую штуку в проект. Полезненько.

**Comment by alyamovsky** [comment]
сложный вопрос, этот скелетон - скорее конструктор, куда каждый может подмешать свое по вкусу. так как я пока blackfire не юзал, отложим добавление на некоторое время
